parse_config:
  layer_names:
    - Default Layer
    - Mouse Layer
    - Function Number Layer
    - Mark Layer
    - Util Layer
    - Arrow Layer
    - Scroll Layer
    - Window Layer

  raw_binding_map:
    '&sys_reset': Reset
    '&bootloader': Boot
    '&caps_word': Caps Word

  zmk_keycode_map:
    # Symbols
    EXCLAMATION: "!"
    EXCL: "!"
    C_PLAY_PAUSE: "▷||"
    SEMICOLON: ";"
    COMMA: ","
    DOT: "."
    SLASH: "/"
    DELETE: "DEL"
    BACKSPACE: "BS"
    SINGLE_QUOTE: "'"
    DOUBLE_QUOTES: "\""
    TILDE: "~"
    GRAVE: "`"
    UNDER: "_"
    COLON: ":"
    PIPE: "|"
    BACKSLASH: "\\"
    AT_SIGN: "@"
    HASH: "#"
    DOLLAR: "$"
    PERCENT: "%"
    CARET: "^"
    AMPERSAND: "&"
    ASTERISK: "*"
    LEFT_PARENTHESIS: "("
    RIGHT_PARENTHESIS: ")"
    LEFT_BRACKET: "["
    RIGHT_BRACKET: "]"
    LEFT_BRACE: "{"
    RIGHT_BRACE: "}"
    PLUS: "+"
    EQUAL: "="
    MINUS: "-"
    LEFT: "←"
    RIGHT: "→"
    UP: "↑"
    DOWN: "↓"


draw_config:
  dark_mode: auto
  glyph_tap_size: 18
  footer_text: 'LisM KEYMAPS | Created with keymap-drawer'
